export const LOADED = 'LOADED'
export const LOADING = 'LOADING'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const IS_AUTHICATED = 'IS_AUTHICATED'
export const DD_TOGGLED = 'DD_TOGGLED'
export const COPY_ANIMATION = 'COPY_ANIMATION'
